export const jewelryData = [
  // 🟣 Necklaces (10)
  { id: 1, category: "Necklace", subcategory: "Women", name: "Eternal Diamond Pendant", stoneType: "Diamond", image: "images/products/1.jpg", price: 420, oldPrice: 520, size: 7 },
  { id: 2, category: "Necklace", subcategory: "Men", name: "Bold Diamond Chain", stoneType: "Diamond", image: "images/products/2.jpg", price: 390, oldPrice: 480, size: 8 },
  { id: 3, category: "Necklace", subcategory: "Women", name: "Ruby Bloom Choker", stoneType: "Ruby", image: "images/products/3.jpg", price: 460, oldPrice: 590, size: 6 },
  { id: 4, category: "Necklace", subcategory: "Unisex", name: "Crimson Soul Chain", stoneType: "Ruby", image: "images/products/4.jpg", price: 350, oldPrice: 430, size: 7 },
  { id: 5, category: "Necklace", subcategory: "Women", name: "Lumière Diamond Collar", stoneType: "Diamond", image: "images/products/5.jpg", price: 520, oldPrice: 640, size: 9 },
  { id: 6, category: "Necklace", subcategory: "Men", name: "Ruby Shield Pendant", stoneType: "Ruby", image: "images/products/6.jpg", price: 410, oldPrice: 500, size: 8 },
  { id: 7, category: "Necklace", subcategory: "Women", name: "Diamond Crescent Drop", stoneType: "Diamond", image: "images/products/7.jpg", price: 490, oldPrice: 580, size: 7 },
  { id: 8, category: "Necklace", subcategory: "Unisex", name: "Ruby Aura Link", stoneType: "Ruby", image: "images/products/8.jpg", price: 360, oldPrice: 440, size: 6 },
  { id: 9, category: "Necklace", subcategory: "Women", name: "Radiant Diamond Strand", stoneType: "Diamond", image: "images/products/9.jpg", price: 550, oldPrice: 660, size: 10 },
  { id: 10, category: "Necklace", subcategory: "Men", name: "Ruby Crest Chain", stoneType: "Ruby", image: "images/products/10.jpg", price: 400, oldPrice: 490, size: 8 },

  // 💍 Rings (15)
  { id: 11, category: "Ring", subcategory: "Couple", name: "Infinity Diamond Ring Set", stoneType: "Diamond", image: "images/products/11.jpg", price: 620, oldPrice: 780, size: 7 },
  { id: 12, category: "Ring", subcategory: "Couple", name: "Ruby Heart Bond Set", stoneType: "Ruby", image: "images/products/12.jpg", price: 580, oldPrice: 740, size: 6 },
  { id: 13, category: "Ring", subcategory: "Women", name: "Diamond Halo Ring", stoneType: "Diamond", image: "images/products/13.jpg", price: 650, oldPrice: 820, size: 6 },
  { id: 14, category: "Ring", subcategory: "Women", name: "Ruby Blossom Ring", stoneType: "Ruby", image: "images/products/14.jpg", price: 590, oldPrice: 760, size: 7 },
  { id: 15, category: "Ring", subcategory: "Men", name: "Diamond Crest Band", stoneType: "Diamond", image: "images/products/15.jpg", price: 520, oldPrice: 640, size: 9 },
  { id: 16, category: "Ring", subcategory: "Men", name: "Ruby Signet Bold", stoneType: "Ruby", image: "images/products/16.jpg", price: 540, oldPrice: 670, size: 10 },
  { id: 17, category: "Ring", subcategory: "Women", name: "Diamond Grace Loop", stoneType: "Diamond", image: "images/products/17.jpg", price: 610, oldPrice: 780, size: 5 },
  { id: 18, category: "Ring", subcategory: "Men", name: "Ruby Steel Band", stoneType: "Ruby", image: "images/products/18.jpg", price: 490, oldPrice: 600, size: 9 },
  { id: 19, category: "Ring", subcategory: "Women", name: "Diamond Bloom Ring", stoneType: "Diamond", image: "images/products/19.jpg", price: 630, oldPrice: 810, size: 6 },
  { id: 20, category: "Ring", subcategory: "Men", name: "Ruby Crown Band", stoneType: "Ruby", image: "images/products/20.jpg", price: 520, oldPrice: 670, size: 8 },
  { id: 21, category: "Ring", subcategory: "Couple", name: "Twin Diamond Love", stoneType: "Diamond", image: "images/products/21.jpg", price: 700, oldPrice: 880, size: 7 },
  { id: 22, category: "Ring", subcategory: "Couple", name: "Ruby Harmony Set", stoneType: "Ruby", image: "images/products/22.jpg", price: 640, oldPrice: 830, size: 6 },
  { id: 23, category: "Ring", subcategory: "Women", name: "Diamond Essence Curve", stoneType: "Diamond", image: "images/products/23.jpg", price: 600, oldPrice: 750, size: 6 },
  { id: 24, category: "Ring", subcategory: "Men", name: "Ruby Core Ring", stoneType: "Ruby", image: "images/products/24.jpg", price: 530, oldPrice: 670, size: 9 },
  { id: 25, category: "Ring", subcategory: "Women", name: "Diamond Horizon Band", stoneType: "Diamond", image: "images/products/25.jpg", price: 650, oldPrice: 820, size: 5 },

  // 🧿 Earrings (10)
  { id: 26, category: "Earrings", subcategory: "Women", name: "Ruby Drop Earrings", stoneType: "Ruby", image: "images/products/26.jpg", price: 380, oldPrice: 460, size: 5 },
  { id: 27, category: "Earrings", subcategory: "Women", name: "Diamond Star Studs", stoneType: "Diamond", image: "images/products/27.jpg", price: 420, oldPrice: 520, size: 6 },
  { id: 28, category: "Earrings", subcategory: "Men", name: "Ruby Stud Set", stoneType: "Ruby", image: "images/products/28.jpg", price: 300, oldPrice: 380, size: 7 },
  { id: 29, category: "Earrings", subcategory: "Men", name: "Diamond Edge Stud", stoneType: "Diamond", image: "images/products/29.jpg", price: 340, oldPrice: 420, size: 8 },
  { id: 30, category: "Earrings", subcategory: "Women", name: "Ruby Petal Hoops", stoneType: "Ruby", image: "images/products/30.jpg", price: 410, oldPrice: 500, size: 6 },
  { id: 31, category: "Earrings", subcategory: "Unisex", name: "Diamond Circle Drops", stoneType: "Diamond", image: "images/products/31.jpg", price: 370, oldPrice: 460, size: 7 },
  { id: 32, category: "Earrings", subcategory: "Women", name: "Ruby Flame Studs", stoneType: "Ruby", image: "images/products/32.jpg", price: 390, oldPrice: 470, size: 5 },
  { id: 33, category: "Earrings", subcategory: "Men", name: "Diamond Twin Piercing", stoneType: "Diamond", image: "images/products/33.jpg", price: 350, oldPrice: 440, size: 8 },
  { id: 34, category: "Earrings", subcategory: "Women", name: "Ruby Rose Drops", stoneType: "Ruby", image: "images/products/34.jpg", price: 420, oldPrice: 520, size: 6 },
  { id: 35, category: "Earrings", subcategory: "Unisex", name: "Diamond Spark Studs", stoneType: "Diamond", image: "images/products/35.jpg", price: 360, oldPrice: 450, size: 7 },

  // ⛓ Bracelets (15)
  { id: 36, category: "Bracelet", subcategory: "Men", name: "Diamond Link Bracelet", stoneType: "Diamond", image: "images/products/36.jpg", price: 480, oldPrice: 580, size: 8 },
  { id: 37, category: "Bracelet", subcategory: "Women", name: "Ruby Charm Bracelet", stoneType: "Ruby", image: "images/products/37.jpg", price: 420, oldPrice: 520, size: 7 },
  { id: 38, category: "Bracelet", subcategory: "Unisex", name: "Diamond Halo Bangle", stoneType: "Diamond", image: "images/products/38.jpg", price: 460, oldPrice: 560, size: 7 },
  { id: 39, category: "Bracelet", subcategory: "Men", name: "Ruby Band Cuff", stoneType: "Ruby", image: "images/products/39.jpg", price: 410, oldPrice: 490, size: 9 },
  { id: 40, category: "Bracelet", subcategory: "Women", name: "Diamond Dream Bangle", stoneType: "Diamond", image: "images/products/40.jpg", price: 500, oldPrice: 620, size: 6 },
  { id: 41, category: "Bracelet", subcategory: "Men", name: "Ruby Edge Band", stoneType: "Ruby", image: "images/products/41.jpg", price: 420, oldPrice: 510, size: 8 },
  { id: 42, category: "Bracelet", subcategory: "Unisex", name: "Diamond Orb Link", stoneType: "Diamond", image: "images/products/42.jpg", price: 450, oldPrice: 550, size: 7 },
  { id: 43, category: "Bracelet", subcategory: "Women", name: "Ruby Lace Charm", stoneType: "Ruby", image: "images/products/43.jpg", price: 470, oldPrice: 590, size: 6 },
  { id: 44, category: "Bracelet", subcategory: "Men", name: "Diamond Core Cuff", stoneType: "Diamond", image: "images/products/44.jpg", price: 480, oldPrice: 580, size: 9 },
  { id: 45, category: "Bracelet", subcategory: "Women", name: "Ruby Chain Elegance", stoneType: "Ruby", image: "images/products/45.jpg", price: 440, oldPrice: 540, size: 7 },
  { id: 46, category: "Bracelet", subcategory: "Unisex", name: "Diamond Light Curve", stoneType: "Diamond", image: "images/products/46.jpg", price: 490, oldPrice: 610, size: 8 },
  { id: 47, category: "Bracelet", subcategory: "Men", name: "Ruby Stone Thread", stoneType: "Ruby", image: "images/products/47.jpg", price: 430, oldPrice: 520, size: 8 },
  { id: 48, category: "Bracelet", subcategory: "Women", name: "Diamond Shimmer Band", stoneType: "Diamond", image: "images/products/48.jpg", price: 500, oldPrice: 630, size: 7 },
  { id: 49, category: "Bracelet", subcategory: "Men", name: "Ruby Crown Loop", stoneType: "Ruby", image: "images/products/49.jpg", price: 410, oldPrice: 500, size: 9 },
  { id: 50, category: "Bracelet", subcategory: "Unisex", name: "Diamond Aura Thread", stoneType: "Diamond", image: "images/products/50.jpg", price: 470, oldPrice: 580, size: 7 }
];