import Footer from "@/components/layout/Footer";
import "./globals.css";
import Navbar from "@/components/layout/Navbar";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="overflow-x-hidden flex flex-col min-h-screen">
  <Navbar />
  <main className="flex-1">
    {children}
  </main>
  <Footer />
</body>
    </html>
  );
}
